steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/helloworld', '.']
    timeout: 400s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/helloworld']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/helloworld-deployment', 'helloworld=gcr.io/${PROJECT_ID}/helloworld']
    env:
       - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
       - 'CLOUDSDK_CONTAINER_CLUSTER=helloworldcluster'
